added task 2
js-tasks-ru/jsbasic-20220418-2_mihaylov-daniil pull request #2
Opened 2022-04-18 20:17 UTC by daniyani

2022-04-18 20:18 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-04-19 09:09 UTC, SinimaWath requested changes

2022-04-19 09:09 UTC, SinimaWath commented on 1-module/2-task/task.test.js
> +  if(name !== null && name !== ''  && name.length >= 4 && name.length === name.replace(/\s/g, '').length) {
`name.length === name.replace(/\s/g, '').length` - нужно заменить на более простую операцию, к примеру:`!name.includes`

2022-04-19 09:09 UTC, SinimaWath commented on 1-module/2-task/task.test.js
> +function isValid(name) {
Не нужно писать код в task.test.js :) Надо только в index.js

2022-04-19 10:38 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-04-19 13:44 UTC, SinimaWath approved these changes

2022-04-19 13:45 UTC, merged